# Generated by Django 5.2.3 on 2025-06-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FilePathField(match='.*\\.(jpg|jpeg|png)$', path='C:\\Users\\llima\\OneDrive\\Área de Trabalho\\api_rest\\api\\movies\\posters', recursive=True),
        ),
    ]
